# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

# Let us list the factors of the first seven triangle numbers:

#     1: 1
#     3: 1,3
#     6: 1,2,3,6
#     10: 1,2,5,10
#     15: 1,3,5,15
#     21: 1,3,7,21
#     28: 1,2,4,7,14,28

# We can see that 28 is the first triangle number to have over five divisors.

# What is the value of the first triangle number to have over five hundred divisors?

# I will be using the following:  If N = p^a * q^b * r^c, then 
# total number of divisors = (a+1)(b+1)(c+1), where p, q and r are the prime factors 

import math 

sum = 0

def is_it_prime(n):
    for i in range(2, int(math.sqrt(n)) + 1):
        if n % i == 0:
            return False 
    return True


def divisors(n):
    prime_factors = {}
    for i in range(1, int(math.sqrt(n)) +1):
        j = 1
        if n % i == 0 and is_it_prime(n) == True: 
            m = n
            while m % i == 0:
                prime_factors[i] = j 
                j += 1
                m = int(m/i)
    number_of_divisors = 1 
    for item in prime_factors.items(): 
        number_of_divisors = number_of_divisors*(item + 1)
    print(prime_factors)
    return number_of_divisors


number_of_divisors = 0
term_of_sequence = 0 
n = 1 
while number_of_divisors <= 6:
     term_of_sequence = int(n*(n+1)/2) 
     number_of_divisors = divisors(term_of_sequence)
     n += 1 
print(number_of_divisors)
print(term_of_sequence)