
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 										1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

sum = 2

i = 1
j = 2
next_term = 0

while next_term <= 4000000:
	if next_term % 2 == 0:
		sum += next_term
		#print(sum)
	next_term = i + j
	i = j
	j = next_term

print(sum)

